spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gachon_community_db_prod?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

springdoc:
  swagger-ui:
    enabled: false

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gachon_community_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

server:
  port: 8080
  address: 0.0.0.0
