nexon:
  openapi:
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJYLUFwcC1SYXRlLUxpbWl0IjoiNTAwOjEwIiwiYWNjb3VudF9pZCI6IjE2Mjc5MzcwNTAiLCJhdXRoX2lkIjoiMiIsImV4cCI6MTY5NTI3MzA5OSwiaWF0IjoxNjc5NzIxMDk5LCJuYmYiOjE2Nzk3MjEwOTksInNlcnZpY2VfaWQiOiI0MzAwMTEzOTMiLCJ0b2tlbl90eXBlIjoiQWNjZXNzVG9rZW4ifQ.GAkNx8UlkfTlPSFeeCJBc1CGuugJnhb45NWcaPDKZMk